### ISSUE TITLE
onPrepareOptionsMenu question

### ISSUE THREAD

**Issue by cj7** [kanytu/android-material-drawer-template#45]
Hi, may i ask you a question. 
i was trying to call the onPrepareOptionsMenu in the NavigationDrawerFragment. 
But i found that the code was not calling. 

Besides,  i try to call the onPrepareOptionsMenu in the main activity, it was called. but the menu is return null.
May i know which code i should use actually, because i saw you have using the 
"   getActivity().supportInvalidateOptionsMenu(); // calls onPrepareOptionsMenu() " in the fragment.
But i dont know which code will call when run the above code.
Thanks.

**Comment by kanytu** [comment]
Hi cj7. 

As you can see NavigationDrawerFragment  doesn't have menu. That's why it was not calling onPrepareOptionsMenu. To enable menus on fragments you have to call setHasOptionsMenu(true) on it. Those invalidate calls you see on the navigation fragment are there to refresh the MainActivity menu which you can use to display a different menu if the drawer is open or closed.

**Comment by cj7** [comment]
Thanks a lot!
